apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
spec:
  rules:
  - host: "mytestcarsapi.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: carsapi-service
            port:
              number: 5000