apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: name
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: mytestcarsapi.com
      http:
        paths:
          - backend:
            serviceName: carsapi-service
            servicePort: 5000