apiVersion: v1
kind: Service
metadata:
  name: carsapi-service
spec:
  type: LoadBalancer
  selector:
    app: carsapi-pod
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: carsapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carsapi-pod
  template:
    metadata:
      labels:
        app: carsapi-pod
    spec:
      containers:
      - name: carsapi-container
        image: dockec2021/cars-api:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 80    