name: Docker build, push and Deploy to Kubernetes cluster

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Compose Build
        run: docker-compose build

      - name: Docker Compose Push Images
        run: docker-compose push

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Save DigitalOcean
        run: doctl kubernetes cluster kubeconfig save 5a93006e-c2c2-40a2-a975-a67db38d5dc8

      - name: Deploy to Kubernetes
        run: |
          kubectl delete all --all
          kubectl apply -f ./.k8s/web-services/carsapi-service.yml
          kubectl apply -f ./.k8s/ingress/ingress-controller.yml